### ISSUE TITLE
heroku list

### ISSUE THREAD

**Issue by jasper-lyons** [daemonsy/hubot-heroku#21]
I'm getting my team into using slack for managing our heroku instances and we are pushing up and removing instances every day. Something that is sorely missing form this is the functionality to list all of the apps accessible by the authorized account.

I would be happy to add some tests for this and implement it but I wanted to let my intentions be known before I embarked on implementing it.

**Comment by daemonsy** [comment]
That sounds like an amazing feature to have. We need something like this too. 

Sorry for the late reply, did you get any headway on this?

**Comment by daemonsy** [comment]
Implemented
